domains_urls:
#    -   id: 1
#        url: http://127.0.0.1:8000
#
#     -   id: 2
#         url: http://127.0.0.2:8000

#domains_urls:
    -   id: 1
        url: https://shopsys.local.tld

    -   id: 2
        url: https://shopsys2.local.tld
