kind: Service
apiVersion: v1
metadata:
    name: rabbitmq
spec:
    selector:
        app: rabbitmq
    ports:
        -   name: management
            port: 15672
            targetPort: 15672
        -   name: rabbitmq
            port: 5672
            targetPort: 5672
