shopsys_shop:
    resource: "@ShopsysShopBundle/Resources/config/routing.yml"
    prefix: /

shopsys_framework:
    resource: "@ShopsysFrameworkBundle/Resources/config/routing.yml"

shopsys_api_v1:
    resource: "@ShopsysBackendApiBundle/Resources/config/v1/routing.yml"

#oauth2:
#    prefix: /api
#    resource: '@TrikoderOAuth2Bundle/Resources/config/routes.xml'
    
elfinder:
    resource: "@FMElfinderBundle/Resources/config/routing.yml"

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }