services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Shopsys\ShopBundle\:
        resource: '../../**/*{Factory}.php'

    CommerceGuys\Intl\NumberFormat\NumberFormatRepository: ~

    Shopsys\FrameworkBundle\Component\Localization\DateTimeFormatter:
        factory: ['@Shopsys\FrameworkBundle\Model\Localization\CustomDateTimeFormatterFactory', create]

    CommerceGuys\Intl\Currency\CurrencyRepositoryInterface:
        class: Shopsys\FrameworkBundle\Model\Localization\IntlCurrencyRepository

    Shopsys\FrameworkBundle\Component\EntityExtension\EntityNameResolver:
        class: Tests\ShopBundle\Functional\EntityExtension\OverwritableEntityNameResolver
        arguments:
            - "%shopsys.entity_extension.map%"

    Tests\ShopBundle\Functional\EntityExtension\OverwritableEntityNameResolver: '@Shopsys\FrameworkBundle\Component\EntityExtension\EntityNameResolver'

    joschi127_doctrine_entity_override.event_subscriber.load_orm_metadata:
        class: Tests\ShopBundle\Functional\EntityExtension\OverwritableLoadORMMetadataSubscriber
        arguments:
            - "@service_container"
            - "%shopsys.entity_extension.map%"
        tags:
            - { name: doctrine.event_subscriber, priority: -10 }

    League\Flysystem\FilesystemInterface: '@main_filesystem'

    Shopsys\FrameworkBundle\Model\Article\ArticleFactoryInterface: '@Shopsys\FrameworkBundle\Model\Article\ArticleFactory'

    Shopsys\FrameworkBundle\Model\Order\Item\OrderItemFactoryInterface: '@Shopsys\FrameworkBundle\Model\Order\Item\OrderItemFactory'

    Shopsys\FrameworkBundle\Model\Product\Availability\AvailabilityDataFactoryInterface: '@Shopsys\FrameworkBundle\Model\Product\Availability\AvailabilityDataFactory'

    Shopsys\FrameworkBundle\Model\Product\Search\Export\ProductSearchExportWithFilterRepository: ~

    Shopsys\ReadModelBundle\Product\Action\ProductActionViewFacade: ~

    Shopsys\ReadModelBundle\Product\Listed\ListedProductViewFacade: ~

    Shopsys\ReadModelBundle\Product\Listed\ListedProductViewFacadeInterface: '@Shopsys\ReadModelBundle\Product\Listed\ListedProductViewElasticFacade'

    Shopsys\FrameworkBundle\Model\Localization\Localization:
        arguments:
            $adminLocale: '%shopsys.admin_locale%'

    Shopsys\FrameworkBundle\Component\Router\DomainRouterFactory:
        arguments: ['%router.resource%']

    Shopsys\FrameworkBundle\Component\CurrencyFormatter\CurrencyFormatterFactory: ~

    Shopsys\FrameworkBundle\Model\Localization\IntlCurrencyRepository: ~

    Shopsys\FrameworkBundle\Twig\NumberFormatterExtension: ~

    Shopsys\FrameworkBundle\Model\Administration\AdministrationFacade: ~

    Shopsys\FrameworkBundle\Model\Pricing\PriceConverter: ~

    Shopsys\FrameworkBundle\Model\Pricing\Rounding: ~
