services:
    _defaults:
        autowire: true

    Shopsys\ShopBundle\DataFixtures\:
        tags: ['doctrine.fixture.orm']
        resource: '../../../DataFixtures/**/*{DataFixture,Loader}.php'

    Shopsys\ShopBundle\DataFixtures\ProductDataFixtureReferenceInjector: ~

    Shopsys\ShopBundle\DataFixtures\Demo\ProductDataFixtureLoader: ~

    Shopsys\ShopBundle\DataFixtures\Demo\ProductParametersFixtureLoader: ~

    Shopsys\ShopBundle\DataFixtures\Performance\CategoryDataFixture:
        arguments:
            - "%shopsys.performance_data.category.counts_by_level%"

    Shopsys\ShopBundle\DataFixtures\Performance\OrderDataFixture:
        arguments:
            - "%shopsys.performance_data.order.total_count%"
            - "%shopsys.performance_data.order.item_count_per_order%"

    Shopsys\ShopBundle\DataFixtures\Performance\ProductDataFixture:
        arguments:
            - "%shopsys.performance_data.product.total_count%"

    Shopsys\ShopBundle\DataFixtures\Performance\UserDataFixture:
        arguments:
            - "%shopsys.performance_data.user.count_per_domain%"

    Shopsys\ShopBundle\DataFixtures\Demo\ImageDataFixture:
        arguments:
            - '%shopsys.data_fixtures_images.resources_dir%'
            - '%shopsys.image_dir%'
            - '%shopsys.domain_images_dir%'
        tags: ['doctrine.fixture.orm']

    Shopsys\ShopBundle\DataFixtures\Demo\ProductDataFixtureCsvReader:
        arguments:
            - '%shopsys.data_fixtures.resource_products_filepath%'

    Shopsys\ShopBundle\DataFixtures\Demo\UserDataFixtureLoader:
        arguments:
            - '%shopsys.data_fixtures.resource_customers_filepath%'